receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55680

exporters:
  otlp/data-prepper:
    endpoint: data-prepper:21890
    tls:
      insecure: true
  #logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/data-prepper]